#Terraform typcal workflow includes - terraform init terraform validate terraform fmt terraform plan  terraform apply
#
#In my scenario, I want two things to happen:
#
#Plan: When a pull request is received, a GitHub Workflow is triggered to perform a security audit,
#construct Google Cloud credentials, load the Terraform CLI, and perform an init , fmt and plan using the
#proposed files in the pull request. Finally, I want a comment on the pull request to show the results of the plan step.
#Apply: When a push is received in the master branch, I can assume that the proposal
#was accepted and the new code should be applied.
#I again wish to construct Google Cloud credentials and load the Terraform CLI.
#However, the final steps will be to apply the configuration.

name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}